### ISSUE TITLE
Implement Analyzer with Support for this proposal

### ISSUE THREAD

**Issue by azenla** [lrhn/dep-optionals#1]
I'm going to try to implement an analyzer that supports this syntax. Perhaps this could be used to make a rewriter for this, or just to test it out.

**Comment by sethladd** [comment]
Still planning to do this?

**Comment by azenla** [comment]
Unfortunately, no, I don't have enough time :(

**Comment by sethladd** [comment]
No worries. Can you close this issue for now?
