### ISSUE TITLE
Not an ideal solution

### ISSUE THREAD

**Issue by mezoni** [lrhn/dep-optionals#3]
``` dart
int parse(String source, [int start = 0, int end], {int radix, int onError(String source)});
```

Better way is to allow an addressing an optional and positional parameters as if they would be named parameters.

``` dart
int parse(String source, [int start = 0, int end, int radix, int onError(String source)]);
```

``` dart
// source, start, onError, radix
var i = int.parse("0x123", 0, onError: ("0x123") => null, radix: 16 );
```

``` dart
int foo(a, [b, c, d, e]);

foo(a, b, d: d);

foo(d: d, a: a);
```

**Comment by lrhn** [comment]
I won't disagree, but that's sadly not a backwards compatible change.

It was how Dart originally worked, but we moved to separate positional and named optional parameters at some point.

**Comment by mezoni** [comment]
> > I won't disagree, but that's sadly not a backwards compatible change.

What will be wrong if as a start point will be allowed use `unnamed` parameters as `named`?
This is not a breaking changes.

``` dart
foo(int x, int y);

var x;
var y;
foo(x, y);
foo(x: x, y: y);
foo(y: y, x: x);
```

This does not breaks an existing code.

**Comment by polux** [comment]
I haven't thought of all the implications but I'm also wondering why we don't simply allow "unnamed" parameters to be passed by name, as in Python and Scala.

**Comment by mezoni** [comment]
Compiler arranges parameters on:
- Required
- Optional

Currently a `required` parameters includes positional parameters, an `optional` parameters includes 'optional' an `named` parameters.
Syntax we don't change but we add new feature (enhancement):
Allow specify `optional` arguments as `named`.

Eg.

``` dart
foo(int a, [int b]);
baz(int a, {int b});

// Old way
foo(a, b);
baz(a, b: b);
// New way w/o breaking changes
// Break existing code?
// Does not break
// Optional by name
foo(a, b: b);

// Break existing code?
// Does not break
// Positional by name
foo(a :a , b: b);
```

Rules:
Required parameters always should be provided in any form (by position or by name):
After when provided pair of name & value the rest also should be as pairs of name & value.

Examples:

``` dart
foo(int x, [int y]);

// The required 'x' provided. OK
foo(x);

// The required 'x' provided. OK
foo(x: x);

// The required 'x' provided. OK
// Error. After pair the next argument also should be pair
foo(x: x, y);

// The required 'x' provided. OK
foo(y: y, x: x);
```

**Comment by mezoni** [comment]
> > I haven't thought of all the implications but I'm also wondering why we don't simply allow "unnamed" parameters to be passed by name, as in Python and Scala.

Every parameter named in Dart.
Only Dart developers think that they anonymous.
What don't allow use any (positional, optional or named) argument by its name?
This does not breaking changes because currently this does not allowed.
This is enhancement.

**Comment by mezoni** [comment]
Compiler creates a list of positional parameters.
When it parses arguments (invocation) it removes each specified positional argument from this list.
If this list becomes empty then all positional parameters specified (form has no sence by position or by name).

Eg.

``` dart
foo(first, second, [third]);

// List [first, second]
// Remove first by position
// Remove second by position
// List is empty. OK
foo(first, second);

// List [first, second]
// Remove first by position
// Remove second by name
// List is empty. OK
foo(first, second: second);


// List [first, second]
// Third not in list. Ignore. Use third by name.
// Disallow by position after by name
// Remove second by name
// Remove first by name
// List is empty. OK
foo(third: third, second: second, first: first);
```

**Comment by a14n** [comment]
@polux Allowing "unnamed" parameters to be passed by name could lead to ambiguities with [Feature Request: Variable Number of Arguments](http://dartbug.com/16253). eg. with `m1(String p1, {String ...rest})`, `m1(p1: "v")` could mean `p1 == "v" && rest.isEmpty` or `p1 == null && rest[#p1] == "v"`.

**Comment by mezoni** [comment]
> > eg. with m1(String p1, {String ...rest}), m1(p1: "v") could mean p1 == "v" && rest.isEmpty or p1 == null && rest[#p1] == "v".

You wrong.
The "p1" is required parameter.
It should to follow before the start of the list of the variable arguments.
Also in a variadic function can be allowed only positional arguments (for avoid the ambiguity):

Eg.
`variadic_fn(positional_args va_list);`

``` dart
// p1 = "v", params = []
m1(p1: "v")

// p1 = "v", params = []
m1("v")

// p1 = "v", params = [a, b ,c]
m1(p: "v", a, b ,c)

// p1 = "v", params = [a, b ,c]
m1("v", a, b ,c)
```

P.S.
Variable arguments are really unnamed arguments.
In fact they are elements of the list.

``` dart
foo(a, b, ... params);

// Params is empty
foo(a, b);

// Params is empty
foo(a: a, b: a);

// Params is empty
foo(b: b, a: a);

// Params is [c]
foo(a, b, c);

// Params is [c]
foo(a: a, b: b, c);

// Params is [c]
foo(b: b, a: a, c);
```

**Comment by a14n** [comment]
@mezoni sorry I meant `m1([String p1], {String ...rest})`

**Comment by mezoni** [comment]
@a14n 

> > @mezoni sorry I meant m1([String p1], {String ...rest})

This impossible in any language.
At least in C and C# becuase this is `ambiguous`.

**Comment by mezoni** [comment]
@a14n 

> > Allowing "unnamed" parameters to be passed by name could lead to ambiguities with Feature Request: Variable Number of Arguments.

This is not a feature request.
This is only issue on the bug tracker with the following flags:
- Type-Enhancement
- Priority-Unassigned
- Area-Language

And it ignored (see flag `Priority-Unassigned`).

It also can be considered not a serious because start with words: **It would be nice to have ...**

And it has a problem because it are based on the wrong conception of the dividing the parameters on the unnamed and named parameters.

**Comment by jmesserly** [comment]
maybe edit issue name? "allow passing any arguments with names"? "remove optional/named distinction"?

@lrhn -- would this make it backwards compatible:

Allow [] and {} to work the same, deprecate one in favor of the other. They can't be combined on the same signature (as today). So your UTC example:

``` dart
DateTime([int year, int month, int day, int hours,
             int minutes, int seconds, int milliseconds,
             bool isUtc]);

new DateTime(year: 2015, isUtc: false) // works now
new DateTime(2015, 4) // still works
```

it "just works" as those become named args. That shouldn't be a breaking change, right? I don't think it changes behavior of any working calls, and it should enable some new ones.

IIRC, there was some concern that developers would use `[int year]` and not think about "year" being part of the public API. Not sure if that's still a concern, but if so could change the behavior of just `{}` and leave `[]` the way it is. Then it would be non-breaking to switch `[]` to `{}`. So if desired, DateTime could switch to:

``` dart
DateTime({int year, int month, int day, int hours,
             int minutes, int seconds, int milliseconds,
             bool isUtc});
```

Seems nice to only have one kind of optional arg. Even if both exist for historical reasons, if there's a way to converge over time, that could be nice.

**Comment by lrhn** [comment]
Even if it was possible to make it backwards compatible, I don't expect Dart to change back to having only one kind of optional parameters.
The problem of having your argument names becoming part of your interface, and it therefore being a breaking change to change the name of a parameter that was only intended as positional, was actually aggravating enough that Dart changed away from that.

I think this proposal has a much better chance of success if it doesn't try to change that back. By all means try to propose the change as a separate proposal (as is already being done).
